### ISSUE TITLE
Request / Replace JsonEditor with successor for easy editing of strings

### ISSUE THREAD

**Issue by theelectricsoul** [fractalf/json-editor-ex#1]
Hello

Thank you for your work on this helpful plugin. :) Much appreciated.

# Problem
The plugin is currently based on the [JsonEditor](https://prod.outgoing.prod.webservices.mozgcp.net/v1/42cd83bf0abcb83beab6069b4bb857a89cd739eb10b3e4a8ac02fc3d555313f6/https%3A//github.com/josdejong/jsoneditor). But the editor does not show strings in a way that allows easy editing.

![image](https://github.com/fractalf/json-editor-ex/assets/10260832/459d9baf-adf7-4073-b02e-a7a29287e9f9)

# Request
The [successor](https://github.com/josdejong/svelte-jsoneditor) of JsonEditor allows easy editing of strings, as strings are displayed without escape sequences.

![image](https://github.com/fractalf/json-editor-ex/assets/10260832/554f1b73-f02c-46a4-9cc7-d017c8c74de3)

Please see video

https://github.com/fractalf/json-editor-ex/assets/10260832/9205557e-b4d9-488e-97f5-b9f7fd176399

**Comment by fractalf** [comment]
Hey!
Thanks for reporting, I will look into this when I get some spare time :)

**Comment by fractalf** [comment]
@theelectricsoul 
Hey buddy, sorry for taking so long. I completely missed that you actually made a video in this report, wow great effort man! In fact that inspired me to start looking at this today :)

So I got it working after a bit of this and that, and also I'm going to add a "dark mode" option. Still need some time to wrap things up, but things are starting to look good. Will probably make it ready this weekend.

What do you think?

![image](https://github.com/fractalf/json-editor-ex/assets/5707457/406678c5-d328-484f-92d4-468458718995)

![image](https://github.com/fractalf/json-editor-ex/assets/5707457/f42326cb-489e-4518-82ef-67140989728b)

**Comment by fractalf** [comment]
I finished the code now and was just about to upload this to Firefox Extensions....
...then I cannot log in :/ 

They seem to have activated a 2FA, which I have no memory of ever activating.
So I wrote them an email and hopefully it will get resolved. Until then ... not much to do

**Comment by theelectricsoul** [comment]
@fractalf 
FAntastic :) I appreciate the work. I would surely use the plugin. :) But as me being a developer myself, I ask myself **"Who will use the plugin over jsoneditoronline.org"**. 

What do you think?

**Comment by fractalf** [comment]
Well, I know its probably pretty safe to use jsoneditoronline.org, but the reason I made this extension was to be 100% certain that the json I work with **does not** leak to the internet. Sometimes I work with customer/client sensitive data that I only want to handle locally.  So I need this for my own work, thats my motivation for making it.

Also, I find it quicker and easier to just press the extension icon to get the "editor" :)

Problem! I cannot log into my firefox developer account. They have activated 2FA which I'm pretty sure I didn't do, so I dont have any codes to log in. I sent them an email, but works case that account is lost and I will have to release this on a new accout..

Mozilla is really starting to loose grip... 

Anyway, will keep you posted here :)

**Comment by fractalf** [comment]
@theelectricsoul 
Today I finally got my account restored! I have now updated the plugin. Thanks for making the issue :)

**Comment by theelectricsoul** [comment]
@fractalf 
No effort on my side but a fart... thank you :)
